version: '3.8'

services:
  backend:
    build: ./backend
    image: smart_mat_backend
    ports:
      - "8080:8080"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: smart_mat_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
