image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  SPRING_PROFILES_ACTIVE: dev

stages:
  #- build-frontend
  - build-backend
  - test
  - deploy

#build-frontend:
#  stage: build-frontend
#  script:
#    - cd ./vue-frontend
#    - docker build -t my-frontend-image -f Dockerfile-test .
#    - docker save my-frontend-image > my-frontend-image-latest.tar

build-backend:
  stage: build-backend
  script:
    - cd ./backend
    - docker build -t my-backend-image -f Dockerfile-test .
    - docker save my-backend-image > my-backend-image-latest.tar

test:
  stage: test
  script:
#    - docker load < my-frontend-image-latest.tar
#    - docker run my-frontend-image
    - docker load < my-backend-image-latest.tar
    - docker run my-backend-image mvn test

deploy:
  stage: deploy
  script:
    - docker load < my-frontend-image-latest.tar
    - docker load < my-backend-image-latest.tar
    - docker-compose up -d
